// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BxyYTxAfQH9hJtvp3r3-ZKUAxpCc5iM',
    appId: '1:829591693767:web:ce3037951fe504ca6611e2',
    messagingSenderId: '829591693767',
    projectId: 'puntopos-c8051',
    authDomain: 'puntopos-c8051.firebaseapp.com',
    storageBucket: 'puntopos-c8051.firebasestorage.app',
    measurementId: 'G-QG9ZZ2E1CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBneTnVKrMn3piGvDrvolf-4gFP8EWSvXQ',
    appId: '1:829591693767:android:2c0a9e686bf82dfa6611e2',
    messagingSenderId: '829591693767',
    projectId: 'puntopos-c8051',
    storageBucket: 'puntopos-c8051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjK4LG5pZhJJCHt7m6vDmTJSjuo6gHOD8',
    appId: '1:829591693767:ios:9f5fa9831f3248626611e2',
    messagingSenderId: '829591693767',
    projectId: 'puntopos-c8051',
    storageBucket: 'puntopos-c8051.firebasestorage.app',
    iosBundleId: 'com.example.stockVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjK4LG5pZhJJCHt7m6vDmTJSjuo6gHOD8',
    appId: '1:829591693767:ios:9f5fa9831f3248626611e2',
    messagingSenderId: '829591693767',
    projectId: 'puntopos-c8051',
    storageBucket: 'puntopos-c8051.firebasestorage.app',
    iosBundleId: 'com.example.stockVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7BxyYTxAfQH9hJtvp3r3-ZKUAxpCc5iM',
    appId: '1:829591693767:web:5421c61e6b4865506611e2',
    messagingSenderId: '829591693767',
    projectId: 'puntopos-c8051',
    authDomain: 'puntopos-c8051.firebaseapp.com',
    storageBucket: 'puntopos-c8051.firebasestorage.app',
    measurementId: 'G-ZEF5YHMVBE',
  );
}
