// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6I6jkGYNhOWOD0hpkSfXLFqXMfXlDzGg',
    appId: '1:326765388647:web:2db250c129518ffd1745c2',
    messagingSenderId: '326765388647',
    projectId: 'puntopos-2088d',
    authDomain: 'puntopos-2088d.firebaseapp.com',
    storageBucket: 'puntopos-2088d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAts-wXlsHS-S8OlMiOKLL3rnICVPjy0ho',
    appId: '1:326765388647:android:41a1906235fc99291745c2',
    messagingSenderId: '326765388647',
    projectId: 'puntopos-2088d',
    storageBucket: 'puntopos-2088d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJs21jEnaplVNCzXITqzkhiX2S5cb3WUE',
    appId: '1:326765388647:ios:f122c61396d682281745c2',
    messagingSenderId: '326765388647',
    projectId: 'puntopos-2088d',
    storageBucket: 'puntopos-2088d.firebasestorage.app',
    iosBundleId: 'com.example.stockVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJs21jEnaplVNCzXITqzkhiX2S5cb3WUE',
    appId: '1:326765388647:ios:f122c61396d682281745c2',
    messagingSenderId: '326765388647',
    projectId: 'puntopos-2088d',
    storageBucket: 'puntopos-2088d.firebasestorage.app',
    iosBundleId: 'com.example.stockVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6I6jkGYNhOWOD0hpkSfXLFqXMfXlDzGg',
    appId: '1:326765388647:web:2eecc58acbb95c0d1745c2',
    messagingSenderId: '326765388647',
    projectId: 'puntopos-2088d',
    authDomain: 'puntopos-2088d.firebaseapp.com',
    storageBucket: 'puntopos-2088d.firebasestorage.app',
  );
}
